print("Hello, World!");
print("Goodbye, World!");
print("-----");
print("Python has left the building.");
print("the party is over!");
print("-----");
print("Python is a popular programming language.");
print("Python is easy to learn and use.");
print("Python is widely used in data analysis, machine learning, and web development.");
print("Python is free and open-source.");
print("Python is developed by Guido van Rossum.");
print("Python is named after the British comedy group Monty Python.");
print("-----");